name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly-2024-01-04
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: wasm-pack build --target web

      - name: Prepare deployment
        run: |
          mkdir -p dist
          cp index.html dist/
          cp -R pkg dist/
          echo "Content of dist directory:"
          ls -R dist

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          rm -rf dist
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
